application: appid
runtime: python27
version: 1
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
- url: /styles.css
  static_files: styles.css
  upload: styles.css
- url: /.*
  script: rialto.application